title: Database
subTitle: 03
image: /assets/person-writing-on-notebook.png
description: greenatlas.earth has created Europe's first open-source database for site owners and parties working in the renewable energy project sector!
button: Coming soon
