#http https and www
http://greenatlas.earth/* https://greenatlas.earth/:splat/index.html 301!
http://www.greenatlas.earth/* https://greenatlas.earth/:splat/index.html 301!
https://www.greenatlas.earth/* https://greenatlas.earth/:splat/index.html 301!
