[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
# http -> https
[[redirects]]
  from = "http://greenatlas.earth/*"
  to = "https://greenatlas.earth/:splat"
  status = 301!
# http+www -> https-www 
[[redirects]]
  from = "http://www.greenatlas.earth/*"
  to = "https://greenatlas.earth/:splat"
  status = 301!
# https+www -> https-www
[[redirects]]
  from = "https://www.greenatlas.earth/*"
  to = "https://greenatlas.earth/:splat"
  status = 301!
