# http -> https
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  # This will be your default build command.
  command = "npm run build"
  # This is where Netlify will look for your lambda functions.
  functions = "functions"
  # This is the directory that you are publishing from.
  publish = "dist"

[[plugins]]
package = "@netlify/plugin-functions-install-core"