title: Database
subTitle: '02'
image: assets/person-writing-on-notebook.png
description: '‘Heeft u behoefte aan een compleet, transparant en onafhankelijk overzicht van de belangrijkste spelers in de Nederlandse en Europese energiemarkt? De zoektool van greenatlas.earth is de eerste open-source database van Europa voor perceeleigenaren en partijen werkzaam binnen de duurzame energieproject sector!'
